version: '3'
services:
  postgresql:
   image: "postgres:11.2-alpine"
   volumes:
    - "./bd/init/:/docker-entrypoint-initdb.d/"
    - "db-data:/var/lib/postgresql/data"
   ports:
    - 6000:5432
   environment:
    - POSTGRES_USER=admin
    - POSTGRES_PASSWORD=admin01
    - POSTGRES_DB=employee_db

volumes:
  db-data:
